FROM golang:1.17 AS builder
WORKDIR /app
COPY . .
ARG CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags '-s -w' cmd/time-checker/main.go

FROM alpine:3.15
WORKDIR /app
RUN apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apk del tzdata
COPY --from=builder /app/main /
ENTRYPOINT ["/main"]
